import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
file1=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\Customer_Dataset.csv")
file2=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\products_dataset.csv")
file3=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\sellers_dataset.csv")
file4=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\orders_dataset.csv")
file5=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\order_items_dataset.csv")
file6=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\order_payments_dataset.csv")
file7=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\order_reviews_dataset.csv")
file8=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\category_name_translation.csv")
file25=pd.merge(file2,file5,on="product_id",how="inner")
file258=pd.merge(file25,file8,on="product_category_name",how="inner")
script_dir=os.path.dirname(os.path.abspath(__file__))
save=os.path.join(script_dir,"Graphs")
def Data_Assessment():
    print(file1.head())
    print(file2.head())
    print(file3.head())
    print(file4.head())
    print(file5.head())
    print(file6.head())
    print(file7.head())
    print(file1.dtypes)
    print(file2.dtypes)
    print(file3.dtypes)
    print(file4.dtypes)
    print(file5.dtypes)
    print(file6.dtypes)
    print(file7.dtypes)
    print(file1.isnull().sum())
    print(file2.isnull().sum()) #Product Category Name has 610 null values
    print(file3.isnull().sum())
    print(file4.isnull().sum())
    print(file5.isnull().sum())
    print(file6.isnull().sum())
    print(file7.isnull().sum())
    print(file1[file1.duplicated()])
    print(file2[file2.duplicated()])
    print(file3[file3.duplicated()])
    print(file4[file4.duplicated()])
    print(file5[file5.duplicated()])
    print(file6[file6.duplicated()])
    print(file7[file7.duplicated()])
def Customer_Analysis():
    file14=pd.merge(file1,file4,on="customer_id",how="inner")
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    count1=file14["customer_city"].value_counts().head(10).index
    sns.countplot(data=file14[file14["customer_city"].isin(count1)],y="customer_city",hue="customer_city",palette="viridis",legend=False)
    plt.xlabel("No. Of Orders Placed", fontsize=11, fontweight="bold")
    plt.ylabel("Customer City", fontsize=11, fontweight="bold")
    plt.title("Top 10 City With Highest No. Of Orders Placed", fontsize=13, fontweight="bold")
    plt.show()
    count2=file14["customer_state"].value_counts().head(10).index
    sns.countplot(data=file14[file14["customer_state"].isin(count2)],y="customer_state",hue="customer_state",palette="viridis",legend=False)
    plt.xlabel("No. Of Orders Placed", fontsize=11, fontweight="bold")
    plt.ylabel("Customer State", fontsize=11, fontweight="bold")
    plt.title("Top 10 State With Highest No. Of Orders Placed", fontsize=13, fontweight="bold")
    plt.show()
    not_delivered = file14[file14["order_status"] != "delivered"]
    count3= not_delivered["customer_city"].value_counts().head(5).index.tolist()
    sns.countplot(data=not_delivered[not_delivered["customer_city"].isin(count3)],x="order_status",hue="customer_city",order=not_delivered["order_status"].value_counts().index)
    plt.xlabel("Order Status", fontsize=11, fontweight="bold")
    plt.ylabel("No. Of Orders", fontsize=11, fontweight="bold")
    plt.legend(title="City")
    plt.title("Top 5 Cities With Orders Not Yet Delivered", fontsize=13, fontweight="bold")
    plt.show()
    count4= not_delivered["customer_state"].value_counts().head(5).index.tolist()
    sns.countplot(data=not_delivered[not_delivered["customer_state"].isin(count4)],x="order_status",hue="customer_state",order=not_delivered["order_status"].value_counts().index)
    plt.xlabel("Order Status", fontsize=11, fontweight="bold")
    plt.ylabel("No. Of Orders", fontsize=11, fontweight="bold")
    plt.legend(title="State")
    plt.title("Top 5 States With Orders Not Yet Delivered", fontsize=13, fontweight="bold")
    plt.show()
def Product_analysis():
    file = file258.dropna().copy()
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    expensive=(file.groupby("product_category_name_english")["price"].sum().sort_values(ascending=False).reset_index().head(10))
    sns.barplot(data=expensive,y="product_category_name_english",x="price",hue="product_category_name_english",palette="viridis",legend=False)
    plt.xlabel("Total Price Of Category In Millions", fontsize=11, fontweight="bold")
    plt.ylabel("Product Category", fontsize=11, fontweight="bold")
    plt.title("Top 10 Most Expensive Product Categories", fontsize=13, fontweight="bold")
    plt.show()
    least_expensive=(file.groupby("product_category_name_english")["price"].sum().sort_values(ascending=True).reset_index().head(10))
    sns.barplot(data=least_expensive,y="product_category_name_english",x="price",hue="product_category_name_english",palette="viridis")
    plt.xlabel("Total Price Of Category", fontsize=11, fontweight="bold")
    plt.ylabel("Product Category", fontsize=11, fontweight="bold")
    plt.title("Top 10 Least Expensive Product Categories", fontsize=13, fontweight="bold")
    plt.show()
    count1=file["product_category_name_english"].value_counts().head(10).index
    sns.countplot(data=file[file["product_category_name_english"].isin(count1)],y="product_category_name_english",hue="product_category_name_english",order=count1,palette="viridis")
    plt.xlabel("No. Of Orders", fontsize=11, fontweight="bold")
    plt.ylabel("Product Category", fontsize=11, fontweight="bold")
    plt.title("Top 10 Most Ordered Product Categories", fontsize=13, fontweight="bold")
    plt.show()
    sns.scatterplot(data=file,x="product_weight_g",y="freight_value",alpha=0.5,color="darkcyan")
    plt.xlabel("Product Weight In Grams", fontsize=11, fontweight="bold")
    plt.ylabel("Freight Value", fontsize=11, fontweight="bold")
    plt.title("Product Freight Value And Weight Correlation", fontsize=13, fontweight="bold")
    plt.tight_layout()
    plt.show()
def Seller_Analysis():
    file35=pd.merge(file3,file5,on="seller_id",how="inner")
    sns.set_style("whitegrid")
    count1=file35["seller_city"].value_counts().head(10).index
    sns.countplot(data=file35[file35["seller_city"].isin(count1)],y="seller_city",hue="seller_city",order=count1,palette="viridis",legend=False)
    plt.xlabel("No. Of Orders", fontsize=11, fontweight="bold")
    plt.ylabel("Seller CIty Name", fontsize=11, fontweight="bold")
    plt.title("Top 10 Highest Selling Cities", fontsize=13, fontweight="bold")
    plt.show()
    count2=file35["seller_state"].value_counts().head(10).index
    sns.countplot(data=file35[file35["seller_state"].isin(count2)],y="seller_state",hue="seller_state",order=count2,palette="viridis",legend=False)
    plt.xlabel("No. Of Orders", fontsize=11, fontweight="bold")
    plt.ylabel("Seller State Name", fontsize=11, fontweight="bold")
    plt.title("Top 10 Highest Selling States", fontsize=13, fontweight="bold")
    plt.show()
    file35["revenue"]=file35["price"]+file35["freight_value"]
    revenue=(file35.groupby("seller_city")["revenue"].sum().sort_values(ascending=False).head(10).reset_index())
    sns.barplot(data=revenue,y="seller_city",x="revenue",hue="seller_city",palette="viridis",legend=False)
    plt.xlabel("Total Revenue Generated In Millions", fontsize=11, fontweight="bold")
    plt.ylabel("Seller City", fontsize=11, fontweight="bold")
    plt.title("Top 10 Cities With Highest Revenue", fontsize=13, fontweight="bold")
    plt.show()
    revenues=(file35.groupby("seller_state")["revenue"].sum().sort_values(ascending=False).head(10).reset_index())
    sns.barplot(data=revenues,y="seller_state",x="revenue",hue="seller_state",palette="viridis",legend=False)
    plt.xlabel("Total Revenue Generated In 10 Millions", fontsize=11, fontweight="bold")
    plt.ylabel("Seller State", fontsize=11, fontweight="bold")
    plt.title("Top 10 States With Highest Revenue", fontsize=13, fontweight="bold")
    plt.show()
def Payment_Analysis():
    sns.set_style("whitegrid")
    count1=file6["payment_type"].value_counts().head(4).index
    sns.countplot(data=file6[file6["payment_type"].isin(count1)],x="payment_type",color="turquoise")
    plt.xlabel("Payment Mode", fontsize=11, fontweight="bold")
    plt.ylabel("No. Of Orders", fontsize=11, fontweight="bold")
    plt.title("Most Common Payment Mode", fontsize=13, fontweight="bold")
    plt.show()
    count2=file6["payment_installments"].value_counts().head(5).index
    sns.countplot(data=file6[file6["payment_installments"].isin(count2)],y="payment_installments",hue="payment_type",palette="viridis")
    plt.ylabel("Payment Installments", fontsize=11, fontweight="bold")
    plt.xlabel("No. Of Orders", fontsize=11, fontweight="bold")
    plt.title("Most Common Installment Plans", fontsize=13, fontweight="bold")
    plt.legend(title="Payment Mode")
    plt.show()
    count3=file6["payment_sequential"].value_counts().head(3).index
    sns.countplot(data=file6[file6["payment_sequential"].isin(count3)],x="payment_sequential",hue="payment_type",palette="viridis")
    plt.xlabel("Payment Sequential", fontsize=11, fontweight="bold")
    plt.ylabel("No. Of Orders", fontsize=11, fontweight="bold")
    plt.title("Most Common Payment Sequential", fontsize=13, fontweight="bold")
    plt.legend(title="Payment Mode")
    plt.show()
def Review_Analysis():
    file257=pd.merge(file25,file7,on="order_id",how="inner")
    file2573=pd.merge(file257,file3,on="seller_id",how="inner")
    sns.set_style("whitegrid")
    count2=file2573["seller_city"].value_counts().head(5).index
    sns.countplot(data=file2573[file2573["seller_city"].isin(count2)],y="seller_city",hue="review_score",palette="viridis")
    plt.xlabel("No. Of Orders", fontsize=11, fontweight="bold")
    plt.ylabel("Seller City", fontsize=11, fontweight="bold")
    plt.legend(title="Review Score")
    plt.title("Review Distribution Over Top 5 Seller Cities", fontsize=13, fontweight="bold")
    plt.show()
    count1=file2573["seller_state"].value_counts().head(5).index
    sns.countplot(data=file2573[file2573["seller_state"].isin(count1)],y="seller_state",hue="review_score",palette="viridis")
    plt.xlabel("No. Of Orders", fontsize=11, fontweight="bold")
    plt.ylabel("Seller State", fontsize=11, fontweight="bold")
    plt.legend(title="Review Score")
    plt.title("Review Distribution Over Top 5 Seller States", fontsize=13, fontweight="bold")
    plt.show()
    file = file258.dropna().copy()
    fileg7=pd.merge(file,file7,on="order_id",how="inner")
    count3=fileg7["product_category_name_english"].value_counts().head(10).index
    sns.countplot(data=fileg7[fileg7["product_category_name_english"].isin(count3)],y="product_category_name_english",hue="review_score",palette="viridis")
    plt.xlabel("No. Of Orders", fontsize=11, fontweight="bold")
    plt.ylabel("Product category", fontsize=11, fontweight="bold")
    plt.title("Top 10 Product Categories With Review Disitribution", fontsize=13, fontweight="bold")
    plt.legend(title="Review Distribution")
    plt.show()
Data_Assessment()
Customer_Analysis()
Product_analysis()
Seller_Analysis()
Payment_Analysis()
Review_Analysis()

