import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
file1=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\Customer_Dataset.csv")
file2=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\products_dataset.csv")
file3=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\sellers_dataset.csv")
file4=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\category_name_translation.csv")
file5=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\orders_dataset.csv")
file6=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\order_items_dataset.csv")
file7=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\order_payments_dataset.csv")
file8=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\order_reviews_dataset.csv")
script_dir=os.path.dirname(os.path.abspath(__file__))
save=os.path.join(script_dir,"Graphs")
def Data_Assessment():
    print(file1.head())
    print(file2.head())
    print(file3.head())
    print(file4.head())
    print(file5.head())
    print(file6.head())
    print(file7.head())
    print(file8.head())
    print(file1.dtypes)
    print(file2.dtypes)
    print(file3.dtypes)
    print(file4.dtypes)
    print(file5.dtypes)
    print(file6.dtypes)
    print(file7.dtypes)
    print(file8.dtypes)
    print(file1.isnull().sum())
    print(file2.isnull().sum()) #Product Category Name has 610 null values
    print(file3.isnull().sum())
    print(file4.isnull().sum())
    print(file5.isnull().sum())
    print(file6.isnull().sum())
    print(file7.isnull().sum())
    print(file8.isnull().sum())
    print(file1[file1.duplicated()])
    print(file2[file2.duplicated()])
    print(file3[file3.duplicated()])
    print(file4[file4.duplicated()])
    print(file5[file5.duplicated()])
    print(file6[file6.duplicated()])
    print(file7[file7.duplicated()])
    print(file8[file8.duplicated()])
def Customer_Analysis():
    file15=pd.merge(file1,file5,on="customer_id",how="inner")
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    count1=file15["customer_city"].value_counts().head(10).index
    sns.countplot(data=file15[file15["customer_city"].isin(count1)],y="customer_city",hue="customer_city",palette="viridis",legend=False)
    plt.xlabel("No. Of Orders Placed")
    plt.ylabel("Customer City")
    plt.title("Top 10 City With Highest No. Of Orders Placed")
    plt.show()
    count2=file15["customer_state"].value_counts().head(10).index
    sns.countplot(data=file15[file15["customer_state"].isin(count2)],y="customer_state",hue="customer_state",palette="viridis",legend=False)
    plt.xlabel("No. Of Orders Placed")
    plt.ylabel("Customer State")
    plt.title("Top 10 State With Highest No. Of Orders Placed")
    plt.show()
    not_delivered = file15[file15["order_status"] != "delivered"]
    count3= not_delivered["customer_city"].value_counts().head(5).index.tolist()
    sns.countplot(data=not_delivered[not_delivered["customer_city"].isin(count3)],x="order_status",hue="customer_city",order=not_delivered["order_status"].value_counts().index)
    plt.xlabel("Order Status")
    plt.ylabel("No. Of Orders")
    plt.legend(title="City")
    plt.title="Top 5 Cities With Orders Not Yet Delivered"
    plt.show()
    count4= not_delivered["customer_state"].value_counts().head(5).index.tolist()
    sns.countplot(data=not_delivered[not_delivered["customer_state"].isin(count4)],x="order_status",hue="customer_state",order=not_delivered["order_status"].value_counts().index)
    plt.xlabel("Order Status")
    plt.ylabel("No. Of Orders")
    plt.legend(title="State")
    plt.title="Top 5 States With Orders Not Yet Delivered"
    plt.show()
Data_Assessment()
Customer_Analysis()

